[tool.black]
line-length = 88  # Houd het leesbaar op standaardbreedte schermen
target-version = ['py38']  # Pas aan op je minimum Python versie
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | migrations
)/
'''

[tool.ruff]
line-length = 88
target-version = "py38"
select = [
    "E",  # pycodestyle (errors)
    "F",  # pyflakes
    "B",  # bugbear
    "I",  # isort
    "C90",  # mccabe complexity
    "N",  # pep8-naming
    "D",  # pydocstyle
    "UP",  # pyupgrade
    "PL",  # pylint
    "RUF",  # Ruff-specific rules
]
ignore = [
    "D100",  # Missing docstring in public module
    "D104",  # Missing docstring in public package
    "D107",  # Missing docstring in __init__
]

[tool.ruff.isort]
known-first-party = ["src", "projectnaam", "utils"]  # Dit moeten de namen zijn van de files met de functies
combine-as-imports = true
force-sort-within-sections = true
lines-between-types = 1

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.flake8-quotes]
inline-quotes = "double"
multiline-quotes = "double"
docstring-quotes = "double"

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"
skip-magic-trailing-comma = false

[tool.ruff.per-file-ignores]
# Bijvoorbeeld: migratiebestanden mogen wat losser zijn
"migrations/*.py" = ["E501", "F401"]
